### ISSUE TITLE
Fuzzy Date Matching?

### ISSUE THREAD

**Issue by sarus** [mguterl/chai-datetime#24]
I'm currently testing timestamps that come back from a database where the timestamp is automatically created based on the time of the insertion/update.

It would be neat if chai-datetime could do a "fuzzy" datetime match where you pass an interval and it would return true if the time is within the given time +/- the interval.

For example,

```
var d1 = new Date(2013, 4, 30, 16, 5),
    d2 = new Date(2013, 4, 30, 17);

// Interval provided in seconds, would match if d1 is within 5 seconds of d2
d1.should.fuzzyEqualTime(d2, '5s');
```

This is sort of a helper method instead of using beforeTime and afterTime so I would understand if you prefer to keep the library slim.  It's not too big of a deal to write a small helper that does this already.

Thanks for a great library!

**Comment by mguterl** [comment]
I've been considering adding more moment support in order to resolve #19. There is also a moment-range library that could probably help with this. I'm going to think about this and I'll try to get back to you soon.

**Comment by tomatau** [comment]
What happened with this?

**Comment by mguterl** [comment]
I would prefer not to add moment as a dependency to this package.
