### ISSUE TITLE
TypeError: date.toDateString is not a function

### ISSUE THREAD

**Issue by lucasfeliciano** [mguterl/chai-datetime#26]
When I try to make the assertion below:

``` javascript
var date1 = '2016-01-01T10:00:14.876Z';
var date2 = new Date(date1);

expect(date1).to.equalDate(date2);
```

I get this exception:

```
     TypeError: date.toDateString is not a function
      at Object.chai.datetime.formatDate (node_modules/chai-datetime/chai-datetime.js:51:17)
      at Assertion.<anonymous> (node_modules/chai-datetime/chai-datetime.js:105:39)
      at Assertion.assert (node_modules/chai/lib/chai/utils/addChainableMethod.js:83:49)
      at Context.<anonymous> (test/middlewares/lookup_response_action.spec.js:9:5708)
```

Any ideas?

**Comment by mguterl** [comment]
@lucasfeliciano I make no attempt to coerce strings into dates. I've been contemplating adding moment to ease some of this pain.

**Comment by lucasfeliciano** [comment]
It would be a nice feature @mguterl. :+1: 

This test that I'm writing is about transforming all my object's dates from dateStrings to dates, I was just checking that if the transformed date is the same as the dateString.

**Comment by austin-bittinger** [comment]
For anyone curious as to a work-around, you can simply write
```javascript
expect(new Date(date1)).to.equalDate(date2));
```
if you are unsure whether date1 will be a date or a string on exit from the function.

**Comment by mguterl** [comment]
I've decided not to add moment as a dependency to this package.
