### ISSUE TITLE
Is This Library Dead?

### ISSUE THREAD

**Issue by machineghost** [mguterl/chai-datetime#34]
It kind of seems like it might be dead because the most recent un-resolved issues are all from 2016 or earlier.

If it's not dead a little documentation of the other functions (eg. in what order do I pass arguments to `withinTime`?) would be handy.

**Comment by mguterl** [comment]
I haven't been using this lately, but I would hesitate to call it dead. Most of the issues surround adding moment.js support which I've wavered back and forth on.

[Here are the tests](https://github.com/mguterl/chai-datetime/blob/master/test/test.js#L564) that you can use for an example for `withinTime`. If you want to make a PR for the README to add docs for `withinTime` I would appreciate it.
