### ISSUE TITLE
Types missing for beforeOrEqualTime

### ISSUE THREAD

**Issue by sqwk** [mguterl/chai-datetime#42]
`@types/chai-datetime@v0.0.36` is missing types for `beforeOrEqualTime` and some other checks. Are these generated from this project or is this a separate (DefinitelyTyped?) project?

**Comment by mguterl** [comment]
Hey @sqwk these types currently come from DefinitelyTyped. In the future I'd be open to adding the types to this project itself or moving this project to TypeScript.
